### ISSUE TITLE
Doesn't work with module names >= 15 characters

### ISSUE THREAD

**Issue by orrc** [cesarferreira/gradlr#1]
I just gave this tool a try, but none of the tasks in our main module `clue-android-app` appeared in the list.

Module names appear to only be detected if they're under an arbitrary(?) [limit of 15 characters](https://github.com/cesarferreira/gradlr/blob/82bd351/cli.js#L91), and ours happens to be 16 characters long... 😄

**Comment by cesarferreira** [comment]
haha that's long :)
Just bumped the value to `25` from `15`.
Update to version `1.1.1` to achieve success 💯
