### ISSUE TITLE
It doesn't work in a Fish shell

### ISSUE THREAD

**Issue by cesards** [cesarferreira/gradlr#2]
I try to execute the command in a fish shell, but it doesn't work. Does it support it?

**Comment by pawegio** [comment]
I use a fish and it works pretty well.

**Comment by cesards** [comment]
```
 ~/D/A/c *$  gradlr                                                                                                                                                                                                                                                         14.2s  Wed  5 Jul 09:39:23 2017
fish: Unknown command 'gradlr
```

**Comment by cesarferreira** [comment]
Hey, if the command is unknown it means you didn't install the tool properly

> npm install -g gradlr

should do the trick

**Comment by cesards** [comment]
I did: 
```
/usr/local/Cellar/node/8.1.3/bin/gradlr -> /usr/local/Cellar/node/8.1.3/lib/node_modules/gradlr/cli.js
+ gradlr@1.1.1
updated 1 package in 13.382s
```

**Comment by cesarferreira** [comment]
This is not related to `gradlr`. This will happen to you for any globally (`node install -g`) package you install, there must something wrong with your node path, I don't know how to help you mate.

**Comment by cesards** [comment]
👍
