### ISSUE TITLE
Select multiple gradle tasks to execute

### ISSUE THREAD

**Issue by pawegio** [cesarferreira/gradlr#3]
I would like to be able to execute multiple gradle tasks synchronously.
(btw. great project, props!)

**Comment by cesarferreira** [comment]
Thanks mate,
I thought about that but didn't had a good idea of how to do it in terms of user experience, how do you suggest?

**Comment by pawegio** [comment]
Maybe with <kbd>Tab</kbd> key to act as an autocomplete for selected task.
I imagine such a flow: 
1. Enter `cl`
2. Use arrows to highlight `clean` task
3. Press <kbd>Tab</kbd>
4. Enter `bui`
5. Press <kbd>Enter</kbd>

... and see `clean build` tasks beeing executed.

**Comment by cesarferreira** [comment]
That's actually a great idea, i'll do it when I have the time :) thanks
